version: '3.5'

services:
  postgres:
    image: postgres:14.4
    restart: always
    volumes: 
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    ports:
      - '5432:5432'


volumes:
  db:
    driver: local